CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(100) NOT NULL,
    isbn VARCHAR(13) NOT NULL UNIQUE,
    publication_year INT NOT NULL,
    total_copies INT NOT NULL,
    available_copies INT NOT NULL
);

CREATE TABLE readers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    registration_date DATE NOT NULL
);

CREATE TABLE bookloans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    book_id BIGINT NOT NULL,
    reader_id BIGINT NOT NULL,
    loan_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE,
    loan_status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES books(id),
    CONSTRAINT fk_reader FOREIGN KEY (reader_id) REFERENCES readers(id)
);

CREATE INDEX idx_books_title_author ON books(title, author);
CREATE INDEX idx_readers_phone ON readers(phone);
CREATE INDEX idx_bookloans_book_reader_status ON bookloans(book_id, reader_id, loan_status);
CREATE INDEX idx_bookloans_reader ON bookloans(reader_id);
CREATE INDEX idx_bookloans_overdue ON bookloans(return_date, due_date);