spring.application.name=My Library
spring.main.banner-mode=off

management.endpoints.web.base-path=/actuator
management.metrics.tags.application=${spring.application.name}

spring.retry.max-attempts=3
spring.retry.backoff.delay=100
spring.retry.backoff.multiplier=2.0
spring.retry.backoff.max-delay=1000

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.flyway.baseline-on-migrate=true
